# Image & Replica Configuration
image:
  repository: docker.io/farhan0911/go-portfolio
  tag: "31224383761"
  pullPolicy: Always

replicaCount: 2

# Resource Requests & Limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Horizontal Pod Autoscaling (HPA) Settings
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Grafana Configuration
grafana:
  grafanaIni:
    smtp:
      enabled: true
      host: "smtp.gmail.com:587"
      user: "mdfarhanraza001@gmail.com"
      password: "mnmq iztm xzxb yvzg"
      skip_verify: true
      from_address: "mdfarhanraza001@gmail.com"
      from_name: "Grafana Alerts"