apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-portfolio-deployment
  labels:
    app: go-portfolio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-portfolio
  template:
    metadata:
      labels:
        app: go-portfolio
    spec:
      containers:
      - name: go-portfolio
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        ports:
        - containerPort: 8080